steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}', '-t',
           'us-west1-docker.pkg.dev/${PROJECT_ID}/gcloud-lite/gcloud-lite:latest',
           '-t', 'us-west1-docker.pkg.dev/${PROJECT_ID}/gcloud-lite/gcloud-lite:${_CLOUD_SDK_VERSION}',
           '.']
images: 'us-west1-docker.pkg.dev/${PROJECT_ID}/gcloud-lite/gcloud-lite'
options:
  logging: CLOUD_LOGGING_ONLY