steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'ci/Dockerfile', '-t',
           'us-west1-docker.pkg.dev/${PROJECT_ID}/tonym-us/gcloud-lite-build:latest', '.']
images: ["us-west1-docker.pkg.dev/${PROJECT_ID}/tonym-us/gcloud-lite-build"]
options:
  logging: CLOUD_LOGGING_ONLY